# Generated by Django 5.0.3 on 2024-06-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Player', max_length=100)),
                ('life_points', models.PositiveIntegerField(default=4000)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red'), ('orange', 'Orange'), ('purple', 'Purple')], max_length=6)),
            ],
        ),
    ]
